// Instalar a extensão "Rest Client" do VSCode

// Configurar o arquivo settings.json do VSCode :
// "rest-client.excludeHostsForProxy": ["localhost","127.0.0.1"]

@urlBase = http://localhost:3000

####################################################
## Autenticação
####################################################

# @name autenticar
#POST {{urlBase}}/auth/get_token
#Content-Type: application/json
#
#{
#  "username": "00000000002",
#  "password": "Agu123456"
#}

###
#@token = {{autenticar.response.body.$.token}}

####################################################

###

# @name listarProdutos
GET {{urlBase}}/products

###

# @name obterProdutoPeloId
GET {{urlBase}}/products/d5d3de57-c590-4735-a745-ba5645e74ab7

###

# @name cadastrarProduto
POST {{urlBase}}/products
Content-Type: application/json

{
    "description": "Caneta Azul",
    "price": 10
}

###

# @name atualizarProduto
PUT {{urlBase}}/products/d5d3de57-c590-4735-a745-ba5645e74ab7
Content-Type: application/json

{
    "description": "Caneta Preta",
    "price": 11
}

###


# @name excluirProduto
DELETE {{urlBase}}/products/d5d3de57-c590-4735-a745-ba5645e74ab7