// Instalar a extensão "Rest Client" do VSCode

// Configurar o arquivo settings.json do VSCode :
// "rest-client.excludeHostsForProxy": ["localhost","127.0.0.1"]

@urlBase = http://localhost:3000

####################################################
## Autenticação
####################################################

# @name autenticar
#POST {{urlBase}}/auth/get_token
#Content-Type: application/json
#
#{
#  "username": "00000000002",
#  "password": "Agu123456"
#}

###
#@token = {{autenticar.response.body.$.token}}

####################################################

###

# @name listarProdutos
GET {{urlBase}}/products

###

# @name obterProdutoPeloId
GET {{urlBase}}/products/6c03d804-781f-46ae-b7b6-bdc708aa57cc

###

# @name cadastrarProduto
POST {{urlBase}}/products
Content-Type: application/json

{
    "description": "Caneta Azul",
    "price": 10
}

###

# @name atualizarProduto
PUT {{urlBase}}/products/c0fdb37a-a47a-4ce4-8d2a-8c90d0a00733
Content-Type: application/json

{
    "description": "Caneta Preta",
    "price": 11
}

###


# @name excluirProduto
DELETE {{urlBase}}/products/67b72fd1181ef0ecd6c3805e