services:
  app:
    container_name: product-microservice
    build:
      context: .
      args:
        http_proxy: ${http_proxy}
        https_proxy: ${https_proxy}
    ports:
      - "3000:3000"
    volumes:
      - ./:/app
      - /app/node_modules  # Evita sobrescrever node_modules do container
    environment:
      http_proxy: ${http_proxy}
      https_proxy: ${https_proxy}
      NODE_ENV: development
      INICIALIZAR_PROJETO: true
    restart: unless-stopped
